// <auto-generated />
using System;
using FitnessApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Data.Migrations
{
    [DbContext(typeof(FitnessAppContext))]
    [Migration("20230917084000_CreateUsers")]
    partial class CreateUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Domain.RunActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RunActivities");
                });

            modelBuilder.Entity("FitnessApp.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bonface",
                            LastName = "Njuguna"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Omondi",
                            LastName = "Wyclife"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Tabby",
                            LastName = "Ayako"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Isaya",
                            LastName = "Mutekhele"
                        });
                });

            modelBuilder.Entity("FitnessApp.Domain.RunActivity", b =>
                {
                    b.HasOne("FitnessApp.Domain.User", null)
                        .WithMany("RunActivities")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("FitnessApp.Domain.User", b =>
                {
                    b.Navigation("RunActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
