// <auto-generated />
using System;
using FitnessApp.Data.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitnessApp.Data.Migrations
{
    [DbContext(typeof(FitnessAppContext))]
    [Migration("20240717083736_DebbugErrorsOnUserTests")]
    partial class DebbugErrorsOnUserTests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FitnessApp.Domain.Entities.Base.SportActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Feeling")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TimeTaken")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SportActivities");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.SensorData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageBodyTemperature")
                        .HasColumnType("float");

                    b.Property<double>("AverageHeartRate")
                        .HasColumnType("float");

                    b.Property<double>("CalorieConsumption")
                        .HasColumnType("float");

                    b.Property<Guid>("SportActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SportActivityId");

                    b.ToTable("SensorDatas");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.UserSportEvent", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SportEventId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SportEventId");

                    b.HasIndex("SportEventId");

                    b.ToTable("UserSportEvents");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entitities.Base.SportEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("SportEvents");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entitities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Base.SportActivity", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entitities.User", "User")
                        .WithMany("SportActivities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.SensorData", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entities.Base.SportActivity", "SportActivity")
                        .WithMany("SensorDatas")
                        .HasForeignKey("SportActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportActivity");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.UserSportEvent", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entitities.Base.SportEvent", "SportEvent")
                        .WithMany("UserSportEvents")
                        .HasForeignKey("SportEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Domain.Entitities.User", "User")
                        .WithMany("UserSportEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entitities.Base.SportEvent", b =>
                {
                    b.HasOne("FitnessApp.Domain.Entitities.User", "User")
                        .WithMany("RegisteredEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitnessApp.Domain.Entitities.User", null)
                        .WithMany("SportEvent")
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entities.Base.SportActivity", b =>
                {
                    b.Navigation("SensorDatas");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entitities.Base.SportEvent", b =>
                {
                    b.Navigation("UserSportEvents");
                });

            modelBuilder.Entity("FitnessApp.Domain.Entitities.User", b =>
                {
                    b.Navigation("RegisteredEvents");

                    b.Navigation("SportActivities");

                    b.Navigation("SportEvent");

                    b.Navigation("UserSportEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
